### PR TITLE
Main2

### PR DESCRIPTION
**Pull request by tylerkim7**
I updated my React!

### CODE REVIEW

**Review by Jiangwei-shi — CHANGES_REQUESTED** [review]
You actually update your React that's good. But do not hand package-lock.json. and package.json. file. I recommend you use Github Desktop app to hand your code. If you still have problem. we can have a short meeting.

**Comment by tylerkim7** [comment]
I deleted my package.json file.

**Review by Jiangwei-shi — CHANGES_REQUESTED** [review]
Do not delete the package-lock.json. Cause what you do is delete the file instead of does not upload the file

**Comment by tylerkim7** [comment]
How's that now? For some reason, .gitignore wouldn't work with my package-lock.json but now it seems to work and have updated it.

**Comment by Jiangwei-shi** [comment]
Do you have time tomorrow? I plan to have a quick lesson to teach some knowledge about uploading new files for new developers.

**Comment by tylerkim7** [comment]
Yes, I have time tomorrow. I am free anywhere from 1-3pm PST and most likely 9-11 pm PST. If that doesn't work for you, we can do this meeting after the weekly Tuesday meeting.

**Comment by Jiangwei-shi** [comment]
How about 3:00pm PST? We can have a quick meeting. around half hour.

**Comment by tylerkim7** [comment]
Hello, 3 pm was when I wasn’t free. How about 5:30 pm?

**Comment by Jiangwei-shi** [comment]
ok meet at 5:30pm

**Comment by tylerkim7** [comment]
sounds good

**Pull request closed without merging**
